#!/usr/bin/env perl

use strict;
use warnings;
use feature 'signatures';
use Symbol 'gensym';
use Template;
use Data::Dumper;
use URI::Escape;
use File::Spec;
use Text::ParseWords qw(shellwords);
use Sub::Util 'subname';
use IPC::Open3;
BEGIN {
    require CGI::Tiny;
}

# XXX i dont like how $cgi is passed around like a cheapwhore

# NOTE: the `git` executable must be available
#        when Git::Repository is loaded
$ENV{PATH} = 'PATH/cgi/';

require 'perl-modules/path.pl';
require 'perl-modules/git.pl';
require 'perl-modules/config-frontend.pl';

our $GLOBAL_CONFIG;

sub serve_template ($cgi, $template_name, $data, $code = 200) {
    my $body;

    my $template = Template->new({
        INCLUDE_PATH => $GLOBAL_CONFIG->{TEMPLATE_ROOT}
    });

    $template->process($template_name, $data, \$body)
        or die "Template: " . $template->error();

    $cgi->set_response_status($code)->render(html => $body);
}

# --- Page handlers
sub serve_index ($cgi) { # /
    serve_template($cgi, "index.tt", {});
}

sub serve_explore ($cgi) { # /explore
    my %data;

    $data{to_link}      = \&repository_to_link;
    $data{to_name}      = \&repository_to_name;
    $data{repositories} = [
        map { s/^$GLOBAL_CONFIG->{GIT_ROOT}\///r }
        @{ directories_at_level($GLOBAL_CONFIG->{GIT_ROOT}, 2) }
    ];

    serve_template($cgi, "explore.tt", \%data);
}

sub serve_user ($cgi, $username) { # /$username/
    my %data;

    $data{username}     = $username;
    $data{to_link}      = \&repository_to_link;
    $data{repositories} = [
        map { s/^$GLOBAL_CONFIG->{GIT_ROOT}\///r }
        @{ directories_at_level("$GLOBAL_CONFIG->{GIT_ROOT}/$username", 1) }
    ];

    serve_template($cgi, "index_user.tt", \%data);
}

sub serve_repository ($cgi, $username, $repository) { # /$username/$repository
    my %data;

    my $host = $cgi->server_name;

    $data{username}     = $username;
    $data{repository}   = $repository;
    $data{h_repository} = new_repository("$GLOBAL_CONFIG->{GIT_ROOT}/$username/$repository.git");
    $data{readme}       = new_readme($data{h_repository});
    $data{clone}        = "$host/~$username/$repository.git";

    serve_template($cgi, "repository.tt", \%data);
}

sub serve_api ($cgi) {
    my $method = $cgi->request_method;

    if ($method eq 'GET') {
        return serve_template($cgi, "api.tt", {});
    }

    if ($method ne 'POST') {
        $cgi->set_response_status(405)->render(
            text => "Method Not Allowed\nOnly GET and POST supported..",
        );
        return;
    }

    my $user = $cgi->param('user') // '';
    my $pass = $cgi->param('pass') // '';
    my $argv = $cgi->param('argv') // '';

    unless ($user && $pass) {
        $cgi->set_response_status(400)->render(
            text => "Bad Request\nMissing user or pass parameter.",
        );
        return;
    }

    my @argv_list = shellwords($argv);

    print STDERR "-- @argv_list --";

    # XXX YOU PLACED SSH INTO PATH EVERYTHING IS FUCKED TOTAL DEATH IMINENT
    my @cmd = (
        'sshpass', '-p', $pass,
        'ssh',
        '-o', 'StrictHostKeyChecking=no',
        '-n',
        "$user\@localhost",
        '-p', '2222',
        @argv_list
    );

    my $output = qx(@cmd); # XXX vuln

    $cgi->render(json => {
        'exit-code' => 1,
        stdout => $output,
        stderr => '', # XXX
    });
}

sub serve_git_http_backend ($cgi, $user, $repo, $tail, $param) {
    # git-http-backend requires the following env vars to function
    #  PATH_INFO and QUERY_STRING are supposedly setup by the webserver,
    #   but lighttpd will refuse to set them if you use the *wrong* kind of
    #   redirection.
    #  It is safe to assume other servers have similar quirks,
    #   therefor we set them explicitly.
    $ENV{GIT_HTTP_EXPORT_ALL} = '1';                          # allow read
    $ENV{GIT_PROJECT_ROOT}    = "$GLOBAL_CONFIG->{GIT_ROOT}"; # root dir of servable repos
    $ENV{PATH_INFO}           = "/$user/$repo.git$tail";      # rel path  to GIT_PROJECT_ROOT + git magick path
    $ENV{QUERY_STRING}        = "$param";                     # e.g. 'service=git-upload-pack'

    # Git debug flags
    #$ENV{GIT_TRACE}        = "2";
    #$ENV{GIT_CURL_VERBOSE} = "1";

    $ENV{PATH} = "$ENV{PATH}:/home/anon/Swap/git/"; # XXX

    # XXX auth check

    exec "/home/anon/Swap/git/git-http-backend"; # XXX exec is a problem for fcgi
}

# ---

sub respect_https_config_requirement ($cgi) {
    if ((!$ENV{'HTTPS'} || $ENV{'HTTPS'} ne 'on') && $GLOBAL_CONFIG->{HTTPS}) {
        $cgi->set_response_status(426)->render(text => 'HTTPS required.');
        exit; # XXX fcgi problem
    }
}

sub handle_cgi ($cgi, $routes, $routes_cache) {
    respect_https_config_requirement($cgi);

    my $uri = $ENV{'REQUEST_URI'} || '/';

	for my $pattern (keys %$routes) {
		if (my @caps = $uri =~ $routes_cache->{$pattern}) {
			my $handler = $routes->{$pattern};
            my @caps = ($#- > 0) ? ($uri =~ /$pattern/) : ();

            print STDERR ">> '$uri' -> " . subname($handler) . "(\$cgi @caps)\n";
			$handler->($cgi, @caps);

            return;
		}
	}

	serve_template($cgi, "404.tt", {}, 404);
}

sub init () {
    my %routes = (
        '/'                                        => \&serve_index,
        '/explore'                                 => \&serve_explore,
        '/api'                                     => \&serve_api,
        '/~([\w]+)'                                => \&serve_user,
        '/~([\w]+)/([\w]+)'                        => \&serve_repository,
        '/~([\w]+)/([\w]+)\.git([^?]*)(?:\?(.*))?' => \&serve_git_http_backend,
    );
    # Regexes are slow, so we precompile them once
    my %routes_cache = map { $_ => qr{^$_$} } keys %routes;

    ConfigFrontend::read_config();

    return \%routes, \%routes_cache;
}

sub main () {
    my ($routes, $routes_cache) = init();
    &CGI::Tiny::cgi(sub {
        my $cgi = $_;
        handle_cgi($cgi, $routes, $routes_cache);
    });
}

main() unless caller;

1;
