#!/usr/bin/env perl

# XXX
# why are we passing around root like a cheap whore?                            because root is where things are (f(x) -> y)        have you considered suicide?
# looking into it, i think we should have a global config object using
# https://metacpan.org/pod/Readonly                                             fuck read only, constants are for faggots           says the nigger who has a "globals are evil phase".
#                                                                                                                                   choose one retard
# i modified the routing heavily, this is how people do it;                     very scary
# pretty clean
# you must also realize that not all routes are necessarily templates,          then they are routed by nginx.                      no you gorilla nigger because of coupling.
# it could be a redirect for example, so the original solution would                                                                you want your server to do a bare minimum
# complicate beyond comprehension                                               ACK.

use strict;
use warnings;
use CGI;
use Template;
use URI::Escape;
use Data::Dumper;
use Git::Repository;
use File::Spec;

$ENV{PATH} = 'cgi_PATH/';
require 'perl-modules/git.pl';
require 'perl-modules/config-frontend.pl';

our $GLOBAL_CONFIG;

sub info {
    warn join(' ', @_);
}

sub serve_template {
    my ($template_name, $data) = @_;

    my $template = Template->new({INCLUDE_PATH => $GLOBAL_CONFIG->{TEMPLATE_ROOT}});

    $template->process($template_name, $data)
        or info("Template: " . $template->error());
}

sub path_to_list_of_directories {
    my $path = $_[0];
    opendir my $dir, $path or die "$path: $!";
    my @directories;
    my %drop = ( # significant dirs only
        '.'  => 0,
        '..' => 0,
    );
    foreach (readdir $dir) {
        push(@directories, $_) if (-d join('/', $_[0], $_) && ($drop{$_} // 1));
    }
    closedir $dir;
    return \@directories;
}

sub collect_all_repositories {
    my $r = [];

    my $directories = path_to_list_of_directories($GLOBAL_CONFIG->{GIT_ROOT});
    for my $d (@$directories) {
        my $subdirectorries = path_to_list_of_directories("$GLOBAL_CONFIG->{GIT_ROOT}/$d");
        for my $sd (@$subdirectorries) {
            push @$r, "$d/$sd";
        }
    }

    return $r;
}

sub repository_to_link {
    my ($repo) = @_;
    my $r = $repo;

    $r =~ s/\.git$//;
    $r = "/~$r";

    return $r;
}

sub repository_to_name {
    my ($repo) = @_;
    my $r = $repo;

    $r =~ s/\.git$//;

    return $r;
}

# --- Page handlers
sub serve_index { # /
    my ($uri) = @_;
    my %data;

    serve_template("index.tt", \%data);
}

sub serve_explore { # /
    my ($uri) = @_;
    my %data;

    $data{repositories} = collect_all_repositories();
    $data{to_link}      = \&repository_to_link;
    $data{to_name}      = \&repository_to_name;

    serve_template("explore.tt", \%data);
}

sub serve_user { # /$username/
    my ($uri, $username) = @_;

    my %data;
    my @directories = @{path_to_list_of_directories(join('/', $GLOBAL_CONFIG->{GIT_ROOT}, $username))};
    # XXX mangle raw directories to valid repository links
    $data{directories} = \@directories;
    $data{username}    = $username;
    if ($data{directories}) { $data{found} = 1; }

    serve_template("index_user.tt", \%data);
}

sub serve_repository { # /$username/$repository
    my ($uri, $username, $repository) = @_;

    my %data;
    $data{username}     = $username;
    $data{repository}   = $repository;
    $data{h_repository} = new_repository("$GLOBAL_CONFIG->{GIT_ROOT}/$username/$repository.git");
    $data{readme}       = new_readme($data{h_repository});

    serve_template("repository.tt", \%data);
}

# ---

sub cgi {
    my ($data, $routes, $routes_cache) = @_;
	my $cgi = CGI->new;
	my %header = (
		-Content_Type => 'text/html',
		-charset      => 'UTF-8',
	);
	my $method = $ENV{'REQUEST_METHOD'} || '';
	my $uri    = $ENV{'REQUEST_URI'} || '/';

    print $cgi->header(%header);
    return if $method eq 'HEAD';

	for my $pattern (keys %$routes) {
		if ($uri =~ $routes_cache->{$pattern}) {
			my $handler = $routes->{$pattern};
			$handler->($uri, $1, $2, $3);
            return;
		}
	}

	serve_template("404.tt", {}); # XXX missing code
}

sub init() {
    my %data = (
        found => 0,
    );

    my %routes = (
        '/'                   => sub { serve_index(@_)      },
        '/explore'            => sub { serve_explore(@_)    },
        '/~([\w.]+)'          => sub { serve_user(@_)       },
        '/~([\w.]+)/([\w.]+)' => sub { serve_repository(@_) },
    );
    # Regexes are slow, so we precompile them once
    my %routes_cache = map { $_ => qr{^$_$} } keys %routes;

    ConfigFrontend::read_config();

    return \%data, \%routes, \%routes_cache;
}

sub main() {
    my ($data, $routes, $routes_cache) = init();
    cgi($data, $routes, $routes_cache);
}

main() unless caller;

1;
