#!/usr/bin/env perl

use strict;
use warnings;
use feature 'signatures';
use Symbol 'gensym';
use Data::Dumper;
use Text::ParseWords qw(shellwords);
use Sub::Util 'subname';
use IPC::Open3;
use Net::OpenSSH;
use Template;
BEGIN {
    # CGI::Tiny wants to Ada us into using it once per process,
    #  however we are C people.
    # The documentation mentions that the `cgi {}` blocks implementation
    #  might change, but realistically it never will and I dont care,
    #  therefor we hack around the package to make it compatible with FCGI.
    require CGI::Tiny;
}

our $cgi;

# The `git` executable must be available
#  when Git::Repository is loaded
$ENV{PATH} = 'PATH/cgi/';

require 'perl-modules/path.pl';
require 'perl-modules/git.pl';
require 'perl-modules/config-frontend.pl';

our $GLOBAL_CONFIG;

sub serve_template ($template_name, $data, $code = 200) {
    my $body;

    my $template = Template->new({
        INCLUDE_PATH => $GLOBAL_CONFIG->{TEMPLATE_ROOT}
    });

    $template->process($template_name, $data, \$body)
        or die "Template: " . $template->error();

    $cgi->set_response_status($code)->render(html => $body);
}

# --- Page handlers
sub serve_index () { # /
    serve_template("index.tt", {});
}

sub serve_explore () { # /explore
    my %data;

    $data{to_link}      = \&repository_to_link;
    $data{to_name}      = \&repository_to_name;
    $data{repositories} = [
        map { s/^$GLOBAL_CONFIG->{GIT_ROOT}\///r }
        @{ directories_at_level($GLOBAL_CONFIG->{GIT_ROOT}, 2) }
    ];

    serve_template("explore.tt", \%data);
}

sub serve_user ($username) { # /$username/
    my %data;

    $data{username}     = $username;
    $data{to_link}      = \&repository_to_link;
    $data{repositories} = [
        map { s/^$GLOBAL_CONFIG->{GIT_ROOT}\///r }
        @{ directories_at_level("$GLOBAL_CONFIG->{GIT_ROOT}/$username", 1) }
    ];

    serve_template("index_user.tt", \%data);
}

sub serve_repository ($username, $repository) { # /$username/$repository
    my %data;

    my $host = $cgi->server_name;

    $data{username}     = $username;
    $data{repository}   = $repository;
    $data{h_repository} = new_repository("$GLOBAL_CONFIG->{GIT_ROOT}/$username/$repository.git");
    $data{readme}       = new_readme($data{h_repository});
    $data{clone}        = "$host/~$username/$repository.git";

    serve_template("repository.tt", \%data);
}

sub serve_api () {
    if ($GLOBAL_CONFIG->{GIT_ROOT}) {
        $cgi->set_response_status(501)->render(
            text => "The API is disabled. This is most likely a read-only service.",
        );
        return;
    }

    my $method = $cgi->request_method;

    if ($method eq 'GET') {
        return serve_template("api.tt", {});
    }

    if ($method ne 'POST') {
        $cgi->set_response_status(405)->render(
            text => "Method Not Allowed\nOnly GET and POST supported.",
        );
        return;
    }

    my $user = $cgi->param('user');
    my $pass = $cgi->param('pass');
    my $argv = $cgi->param('argv');

    unless ($user && $pass && $argv) {
        $cgi->set_response_status(400)->render(
            text => "Bad Request\nMissing parameter.",
        );
        return;
    }

    my $exit_code = -1;
    my $stdout    = '';
    my $stderr    = '';
    my @argv_list = shellwords($argv);

    my $ssh = Net::OpenSSH->new(
        "$user\@127.0.0.1",
        port          => 2222,
        ssh_cmd       => '/usr/bin/ssh',
        password      => $pass,
        master_opts   => ['-o', 'StrictHostKeyChecking=no'],
        timeout       => 2,
    );

    if ($ssh->error) {
        $stdout = $ssh->error;
        goto end;
    }

    ($stdout, $stderr) = $ssh->capture2(@argv_list);
    $exit_code         = $? >> 8;

    if ($ssh->error) {
        $stdout = $ssh->error;
        goto end;
    }

  end:
    $ssh->disconnect;
    $cgi->render(json => {
        'exit-code' => $exit_code,
        stdout      => $stdout,
        stderr      => $stderr,
    });
}

sub serve_git_http_backend ($user, $repo, $tail, $param) {
    # git-http-backend requires the following env vars to function
    #  PATH_INFO and QUERY_STRING are supposedly setup by the webserver,
    #   but lighttpd will refuse to set them if you use the *wrong* kind of
    #   redirection.
    #  It is safe to assume other servers have similar quirks,
    #   therefor we set them explicitly.
    $ENV{GIT_HTTP_EXPORT_ALL} = '1';                          # allow read
    $ENV{GIT_PROJECT_ROOT}    = "$GLOBAL_CONFIG->{GIT_ROOT}"; # root dir of servable repos
    $ENV{PATH_INFO}           = "/$user/$repo.git$tail";      # rel path  to GIT_PROJECT_ROOT + git magick path
    $ENV{QUERY_STRING}        = "$param";                     # e.g. 'service=git-upload-pack'

    ## Git debug flags
    #$ENV{GIT_TRACE}        = "2";
    #$ENV{GIT_CURL_VERBOSE} = "1";

    $ENV{PATH} = "$ENV{PATH}:/home/anon/Swap/git/"; # XXX

    # XXX auth check

    exec "/home/anon/Swap/git/git-http-backend"; # XXX exec is a problem for fcgi
}

# ---

sub respect_https_config_requirement () {
    if ((!$ENV{'HTTPS'} || $ENV{'HTTPS'} ne 'on') && $GLOBAL_CONFIG->{HTTPS}) {
        $cgi->set_response_status(426)->render(text => 'HTTPS required.');
        exit; # XXX fcgi problem
    }
}

sub handle_cgi ($routes, $routes_cache) {
    respect_https_config_requirement();

    my $uri = $ENV{'REQUEST_URI'} || '/';

    for my $pattern (keys %$routes) {
        if (my @caps = $uri =~ $routes_cache->{$pattern}) {
            my $handler = $routes->{$pattern};
            my @caps = ($#- > 0) ? ($uri =~ /$pattern/) : ();

            print STDERR ">> '$uri' -> " . subname($handler) . "(@caps)\n";
            $handler->(@caps);

            return;
        }
    }

    print STDERR ">> '$uri' -> 404\n";
    serve_template("404.tt", {}, 404);
}

sub init () {
    # Regexes are slow, so we precompile them once
    my %routes = (
        '/'                                        => \&serve_index,
        '/explore/?'                               => \&serve_explore,
        '/api/?'                                   => \&serve_api,
        '/~([\w]+)/?'                              => \&serve_user,
        '/~([\w]+)/([\w]+)/?'                      => \&serve_repository,
        '/~([\w]+)/([\w]+)\.git([^?]*)(?:\?(.*))?' => \&serve_git_http_backend,
    );
    my %routes_cache = map { $_ => qr{^$_$} } keys %routes;

    ConfigFrontend::read_config();

    return \%routes, \%routes_cache;
}

sub main () {
    my ($routes, $routes_cache) = init();
    &CGI::Tiny::cgi(sub {
        local $cgi = $_;
        handle_cgi($routes, $routes_cache);
    });
}

main() unless caller;

1;
