#!/usr/bin/env python3
"""
gn-daemon: Gorillanest daemon accepting commands over SSH
"""

import os
import subprocess
import logging
import shlex
import asyncio
import asyncssh
from configobj import ConfigObj
from sys import exit
from os import environ

GLOBAL_CONFIG = {
    'GIT_ROOT'      : None,
    'HOST_KEY_PATH' : None,
    'LISTEN_ADDR'   : None,
    'LISTEN_PORT'   : None,
}

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("gn-daemon")

def validate_password(username, password):
    # XXX
    log.info("auth %s : %s", username, password)
    return username == "anon" and password == "passwd"

# Implementing AsyncSSH functionality is done primarily though polymorphism.
#  This is the class it expects.
#  Complete function definitions are moved out so that
#   this class doesn't dominate the script,
#   and its never in question what should and should not be inside it.
class GNServer(asyncssh.SSHServer):
    def begin_auth(self, username):    return True
    def password_auth_supported(self): return True

    def validate_password(self, username, password):
        return validate_password(username, password)
# ---

def ensure_host_key(path: str) -> str:
    if os.path.exists(path): return path

    log.info("Generating ephemeral host key (saved to %s)", path)
    key = asyncssh.generate_private_key('ssh-rsa')
    with open(path, "wb") as f: f.write(key.export_private_key())
    os.chmod(path, 0o600)

    return path

def validate_client_process(cmd : str) -> [str]:
    # Alternatively, a whitelist could be deployed.
    #  While it is theoretically safer, it was judged to be a safety-theater.
    argv = shlex.split(cmd)
    argv[0] = "PATH/daemon/" + argv[0]

    return argv

async def gn_process(proc : asyncssh.SSHServerProcess):
    cmd = proc.command

    async def pump(reader, writer, label):
        while True:
            data = await reader.read(4096)
            if not data: break
            data_str = data
            if isinstance(data, bytes):
                data_str = data.decode('utf-8')
            #log.info('\033[32m' + label + ' ' + data_str + '\033[0m')
            writer.write(data)
            await writer.drain()

    env = environ.copy()
    env['USERNAME'] = proc.get_extra_info('username')
    env['GIT_ROOT'] = GLOBAL_CONFIG['GIT_ROOT']

    sub = await asyncio.create_subprocess_exec(
        *validate_client_process(cmd),
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env=env
    )

    await asyncio.gather(
        pump(proc.stdin, sub.stdin,   " >> "),
        pump(sub.stdout, proc.stdout, " << "),
        pump(sub.stderr, proc.stderr, " << ")
    )

    rc = await sub.wait()
    proc.exit(rc)

async def start_server():
    host_key_path = ensure_host_key(GLOBAL_CONFIG['HOST_KEY_PATH'])

    await asyncssh.create_server(
        GNServer,
        GLOBAL_CONFIG['LISTEN_ADDR'],
        GLOBAL_CONFIG['LISTEN_PORT'],
        server_host_keys=[host_key_path],
        process_factory=gn_process,
        encoding=None
    )

    await asyncio.Future()

def init():
    global GLOBAL_CONFIG

    config      = ConfigObj('config.default.ini')
    user_config = ConfigObj('config.ini')
    config.merge(user_config)

    config_dict = {}
    config_dict.update(config.get('core', {}).items())
    config_dict.update(config.get('ssh', {}).items())
    
    for k, v in config_dict.items():
        if k in GLOBAL_CONFIG:
            GLOBAL_CONFIG[k] = v
        else:
            log.fatal(f"unknown config key used '{k}'")
            exit(1)

if __name__ == "__main__":
    init()
    try: asyncio.run(start_server())
    except (OSError, asyncssh.Error) as exc:
        log.error("Error starting server: %s", exc)
