#!/usr/bin/env python3
"""
gn-daemon: Gorillanest daemon accepting commands over SSH

# XXX: you either do whitelisting or PATH mangling.
#       both do not make sense.
#       however we need some kind of mechanism to find system executables.
#       it sounds niggericous to have wrappers that simply look up the exe.
#       maybe some kind of caching?
"""
import asyncio
import os
import asyncssh
import subprocess
import logging
import shlex
from sys import exit

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("gn-daemon")

HOST_KEY_PATH = "gn_host_key"   # XXX
LISTEN_ADDR = "0.0.0.0"
LISTEN_PORT = 2222

def validate_password(username, password):
    log.info("auth %s : %s", username, password)
    return username == "anon" and password == "passwd"

# Implementing AsyncSSH functionality is done primarily though polymorphism.
#  This is the class it expects.
#  Complete function definitions are moved out so that
#   this class doesn't dominate the script,
#   and its never in question what should and should not be inside it.
class GNServer(asyncssh.SSHServer):
    def begin_auth(self, username):    return True
    def password_auth_supported(self): return True

    def validate_password(self, username, password):
        return validate_password(username, password)
# ---

def ensure_host_key(path: str) -> str:
    if os.path.exists(path): return path

    log.info("Generating ephemeral host key (saved to %s)", path)
    key = asyncssh.generate_private_key('ssh-rsa')
    with open(path, "wb") as f: f.write(key.export_private_key())
    os.chmod(path, 0o600)

    return path

def validate_client_process(cmd : str) -> [str]:
    argv = shlex.split(cmd)

    # XXX only allow word chars and -
    #if argv[0] not in COMMAND_WHITELIST:
    #    raise ValueError(f"Illegal command ('{argv[0]}') requested.")

    # XXX
    argv[0] = "PATH/daemon/" + argv[0]

    return argv

async def gn_process(proc : asyncssh.SSHServerProcess):
    cmd = proc.command

    async def pump(reader, writer, label):
        while True:
            data = await reader.read(4096)
            if not data: break
            data_str = data
            if isinstance(data, bytes):
                data_str = data.decode('utf-8')
            log.info('\033[32m' + label + ' ' + data_str + '\033[0m')
            writer.write(data)
            await writer.drain()

    sub = await asyncio.create_subprocess_exec(
        *validate_client_process(cmd),
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    await asyncio.gather(
        pump(proc.stdin, sub.stdin, " >> "),
        pump(sub.stdout, proc.stdout, " << "),
        pump(sub.stderr, proc.stderr, " << ")
    )

    rc = await sub.wait()
    proc.exit(rc)

async def start_server():
    host_key_path = ensure_host_key(HOST_KEY_PATH)

    await asyncssh.create_server(
        GNServer,
        LISTEN_ADDR,
        LISTEN_PORT,
        server_host_keys=[host_key_path],
        process_factory=gn_process,
        encoding=None
    )

    await asyncio.Future()

if __name__ == "__main__":
    try: asyncio.run(start_server())
    except (OSError, asyncssh.Error) as exc:
        log.error("Error starting server: %s", exc)
