#!/usr/bin/perl
require 'perl-modules/config-frontend.pl';

our $GLOBAL_CONFIG;
ConfigFrontend::read_config();

my $lighttpd_config_path;

if ($ENV{'DEBUG'} || $GLOBAL_CONFIG->{'USE_CGI'} ) {
    $lighttpd_config_path = './service/lighttpd-cgi.conf';
} else {
    $lighttpd_config_path = './service/lighttpd-fcgi.conf';
}

exec qx( lighttpd -D -f $lighttpd_config_path );
