#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"

CGI='./perl/cgi.pl'
FCGI='./perl/fcgi.pl'

run=$FCGI

while [ ! -z $1 ]; do
    if [ $1 = '-cgi' ]; then
        run=$CGI
    elif [ $1 = '-fcgi' ]; then
        run=$FCGI
    else break; fi
    shift
done

$run $@

# I'm a fan for linguistic redundancy in software
# This is technically a mental disorder
