#!/usr/bin/env perl

use strict;
use warnings;

use CGI;
use FCGI;
use Switch::Back;
use Syntax::Keyword::Try;
use Sys::Syslog;
use Template;
use URI::Escape;
use DBI;
use Cwd qw();

sub info {
    syslog("info", join(' ', @_));
}

# significant dirs only
sub GN::directories {
    opendir my $dir, $_[0] or die "Cannot open directory: $!";
    my @directories;
    foreach (readdir $dir) {
        my %drop = (
            '.'  => 0,
            '..' => 0,
            );
        push(@directories, $_) if (-d join('/', $_[0], $_) && ($drop{$_} // 1));
    }
    closedir $dir;
    return \@directories;
}

# probably should output all repos recursively, currently just outputs list of users
sub GN::index { # /
    my ($template, $root, $dataref) = @_;
    my %data = %$dataref;
    print "* index\n";
    my @directories = @{GN::directories($root)};
    print "@directories\n";
}

sub GN::user { # /$username/
    my ($template, $root, $dataref) = @_;
    my %data = %$dataref;
    print "* user: $data{name}\n";
    my @directories = @{GN::directories(join('/', $root, $data{name}))};
    print "@directories\n";
}

sub GN::repository { # /$username/(.*?(\.git)?)
    my ($template, $root, $dataref) = @_;
    my %data = %$dataref;
    print "* repository: $data{repository}\n";
    my @directories = @{GN::directories(join('/', $root, $data{name}, $data{repository}))};
    print "@directories\n";
}

sub GN::cache { # cache{'/some/path'}

}

openlog("gorillanest", "ndelay,pid", Sys::Syslog::LOG_DAEMON);
try {
    my $gitroot = 'git';
    my $dbfile = 'gorillanest.sqlite3';
    my %data; # useful for minimizing passing and for templating, put default configuration details meant to go on the page in this thing note that it's rw
    #
    my $request = FCGI::Request();
    my $template = Template->new({INCLUDE_PATH => 'template'});
    my $db = DBI->connect("dbi:SQLite:dbname=$dbfile","","", {
        RaiseError => 1,
        AutoCommit => 1,
        sqlite_see_if_its_a_number => 1,
                         }) or die $DBI::errstr;
    #     $db->do(
    # "CREATE TABLE IF NOT EXISTS users (
    #         id INTEGER PRIMARY KEY AUTOINCREMENT,
    #         name TEXT NOT NULL CHECK(length(name) <= 32),
    #         pass TEXT NOT NULL CHECK(length(pass) <= 128
    #                              AND length(pass) >= 32),
    #                                  UNIQUE(name))");
    # my $sth = $db->prepare("INSERT INTO users (name, pass) VALUES (?, ?)");
    # $sth->execute("test", "PUM6w22pxoGVB03qlgEUVBumYgPL2RTGqegoz8vZf7jpsqRQahC3d2OXOH3qFnvo");
    # $db->disconnect;
    #
    my $head = 0;
    while($request->Accept() >= 0) {
        my $cgi = CGI->new;
        my %header = (
            -Content_Type => 'text/plain',
            -charset      => 'UTF-8',
            );
        my $method = $ENV{'REQUEST_METHOD'} || '';
        my $uri = $ENV{'REQUEST_URI'} // '/';
        if ($method eq 'HEAD') {
            $head = 1;
        } elsif ($method eq 'GET') {
            ($data{name}, $data{repository}) = $uri =~ m{/(.*?)/(?:(.*))?};
            info("name:", $data{name} || '', "repo:", $data{repository} || '');
            if ($head) { $head = 0; continue; }
            if ($uri eq '/') {
                print $cgi->header(%header);
                GN::index($template, $gitroot, \%data);
            } elsif ($data{repository}) { # this will generally fail
                print $cgi->header(%header);
                GN::repository($template, $gitroot, \%data);
            } elsif ($data{name}) { # this acts like a default case
                print $cgi->header(%header);
                GN::user($template, $gitroot, \%data);
            } else {
                $header{-status} = '404 Not Found';
                print $cgi->header(%header);
            }
        } else {
            $header{-status} = '405 Method Not Allowed';
            print $cgi->header(%header);
        }
    }
} catch ($error) {
    info("Crashed: $error");
}
