server.modules = (
    "mod_cgi",
    "mod_rewrite",
    "mod_setenv"
)

server.document-root = var.CWD
server.port = 5050

url.rewrite-once = (
    "/(.*).css" => "/www/static/$1.css",
    "/(.*).js"  => "/www/static/$1.js",
    "/(.*).png" => "/www/static/$1.png",
    "/(.*).ico" => "/www/static/$1.ico",
    "/" => "/gn-cgi"
)

setenv.add-environment = (
    "PERL5LIB" => env.PERL5LIB
)

cgi.assign = (
    "gn-cgi" => "/usr/bin/perl"
)

# SSL
#server.modules += (
#    "mod_openssl"
#)
#$SERVER["socket"] == ":5050" {
#    ssl.engine  = "enable"
#    ssl.pemfile = ".env/gn.pem"
#}
