server.modules = (
    "mod_cgi",
    "mod_rewrite",
    "mod_setenv"
)

server.document-root = var.CWD
server.port = 5050

url.rewrite-once = (
    "/" => "/perl/cgi.pl"
)

setenv.add-environment = (
    "PERL5LIB" => env.PERL5LIB
)

cgi.assign = (
    ".pl" => "/usr/bin/perl"
)
