#!/usr/bin/perl
# We use git hooks, specifically post-receive to act as a push mirror.
# These hooks are only skelingtons, they only exec the real handler.
# They also have to get there somehow.
# This script installs them.
# For now it has to be run by hand, eventually the service start up should handle it.
# Note that the hooks depend on the installation directory of GN as of running this script.
use strict;
use warnings;
use feature 'signatures';
use File::Basename;
use File::Slurp 'slurp', 'write_file';
use Cwd qw(realpath);
use Getopt::Long;

my $force = 0;
my $git_root;

GetOptions(
    'force'      => \$force,
    'git-root=s' => \$git_root,
) or die "Usage: $0 [--force] --git-root PATH\n";

die "Error: --git-root is required\n" unless defined $git_root;

# Init
my $meta_line = '# GORILLANEST POST-RECEIVE-HOOK v2';
my $post_receive_hook = join ("\n", (
    '#!/bin/sh',
    $meta_line,
    'exec ' . dirname(realpath($0)) . 'gorillanest/utility/sync-git-repository-to-remotes "$PWD"'
));

sub write_post_receive_hook ($path) {
    write_file($path, {perms => 0766}, $post_receive_hook);
}

# Install
for my $repo (glob($git_root . '/*/*.git')) {
    unless (-d $repo . '/hooks') {
        print STDERR "Hooks directory missing at '$repo'. Ignoring repository.\n";
        next;
    }

    my $post_receive_hook_path = $repo . '/hooks/post-receive';
    if (-e $post_receive_hook_path) {
        my $existing_post_receive_hook = slurp($post_receive_hook_path);
        if ($post_receive_hook eq $existing_post_receive_hook) {
            print STDERR "Already installed at '$repo'.\n";
        } else {
            if ($force || index($existing_post_receive_hook, $meta_line) != -1) {
                write_post_receive_hook($post_receive_hook_path);
                print STDERR "Replaced mismatched GN hook at '$repo'.\n";
            } else {
                print STDERR "Found existing hook at '$repo'. Cowardly refusing to overwrite.\n";
            }
        }
    } else {
        write_post_receive_hook($post_receive_hook_path);
        print STDERR "Installed at '$repo'.\n";
    }
}
