#!/usr/bin/perl

use strict;
use warnings;
use File::Path qw(remove_tree);

sub eecho {
    print STDERR @_;
    exit 1;
}

my $parent_path = $ENV{GIT_ROOT} . '/' . $ENV{USERNAME};
my $repo_name   = $ARGV[0] // '';

$repo_name =~ /^([A-Za-z0-9_]+)$/;
$repo_name = $1;

if ( ! $parent_path
||   ! $repo_name ) {
    eecho "Usage error.";
}

my $repo_path = "$parent_path/$repo_name.git";

if ( ! -d "$repo_path" ) {
    eecho "Repositry marked for deletion '$repo_path' does not exist.";
}

remove_tree $repo_path;
