#!/usr/bin/perl

use strict;
use warnings;

sub eecho {
    print STDERR @_;
    exit 1;
}

my $parent_path = $ENV{GIT_ROOT} . '/' . $ENV{USERNAME};
my $repo_name   = $ARGV[0] // '';

if ( $repo_name =~ /([A-Za-z0-9_-]+)/ ) {
    $repo_name = $1;
}

if ( ! $parent_path
||   ! $repo_name ) {
    eecho "Usage error.";
}

if ( ! -d "$parent_path" ) {
    print "Parent path '$parent_path' does not exist. Creating it...";
    mkdir -p "$parent_path" or eecho "Failed to create parent directory";

}

my $repo_path = "$parent_path/$repo_name.git";

if ( -d "$repo_path" ) {
    eecho "Repository '$repo_path' already exists!";
}

system('git-init', '--bare', $repo_path) == 0 or eecho "Failed to initialize bare repo";
