#!/bin/sh

PARENT_PATH="$GIT_ROOT/$USERNAME"
REPO_NAME="$1"

eecho() {
    echo $* >> /dev/stderr
    exit 1
}

if [ -z "$PARENT_PATH" ] || [ -z "$REPO_NAME" ]; then
    eecho "Usage error."
fi

if [ ! -d "$PARENT_PATH" ]; then
    echo "Parent path '$PARENT_PATH' does not exist. Creating it..."
    mkdir -p "$PARENT_PATH" || { eecho "Failed to create parent directory"; }
fi

REPO_PATH="$PARENT_PATH/$REPO_NAME.git"

if [ -d "$REPO_PATH" ]; then
    eecho "Repository '$REPO_PATH' already exists!"
    exit 1
fi

git init --bare "$REPO_PATH" || { eecho "Failed to initialize bare repo"; }
